Package.describe({
  name: 'robdooh:tycho',
  summary: 'Description of package amazingness',
  version: '0.1.0',
  git: 'https://github.com/rdooh/meteor-tycho',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  // Meteor releases below this version are not supported
  api.versionsFrom("1.2.0.1");

  // Core packages and 3rd party packages
  api.use("jagi:astronomy@1.2.7");

  // The files of this package
  api.addFiles("shared/index.js", ["client", "server"]);

  // The variables that become global for users of your package
  api.export("log", ["client", "server"]);
});

Package.onTest(function (api) {
  var testPackages = [
    'ecmascript',
    'sanjo:jasmine@0.20.3',
    'mongo',
    'stevezhu:lodash',
    'jagi:astronomy@1.2.7',
    'jagi:astronomy-validators@1.1.2',
    'jagi:astronomy-timestamp-behavior@1.1.0'
  ];
  api.use(testPackages);
  api.use('robdooh:tycho');

  api.addFiles("tests/jasmine/server/integration/index.js", ["client", "server"]);
});

/* Generated by okgrow:package-kitchen */
