Package.describe({
  name: 'robdooh:tycho',
  summary: 'Description of package amazingness',
  version: '0.1.0',
  git: 'https://github.com/rdooh/meteor-tycho',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  // Meteor releases below this version are not supported
  api.versionsFrom("1.2.0.1");

  // Core packages and 3rd party packages
  api.use("ddp");
  api.use("tracker");
  api.use("jagi:atmosphere");

  // The files of this package
  api.addFiles("shared/index.js", ["client", "server"]);

  // The variables that become global for users of your package
  api.export("log", ["client", "server"]);
});

Package.onTest(function (api) {
  api.use("tinytest");
  api.use("robdooh:tycho");
  api.addFiles("tests/shared/index.js", ["client", "server"]);
});

/* Generated by okgrow:package-kitchen */
